[package]
name = "monai_computer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10" }
rand = { version = "0.8" }
naia-bevy-client = { version = "0.20", features = ["transport_webrtc"] }
monai_store = { path = "../../store" }
dfdx = { version = "0.11.1" }